services:
  addressservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "${ADDRESS_PORT}:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  orderservice:
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_GATE_PORT
      - API_GATE_ENDPOINT=http://localhost
     ports:
      - "${ORDER_PORT}:8080"
     volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  productservice:
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
     ports:
      - "${PRODUCT_PORT}:8080"
     volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  userservice:
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
     ports:
      - "${USER_PORT}:8080"
     volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  orderapigate:
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
     ports:
      - "${API_GATE_PORT}:8080"
     volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
